// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNHSyxSR1BN8AMZgUI0g9d_11ILLv45JA',
    appId: '1:274514992002:android:deb28e1c360b561900cd9b',
    messagingSenderId: '274514992002',
    projectId: 'flutter-prime-df1c5',
    storageBucket: 'flutter-prime-df1c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcwfCcKBGvY892deYiQ45soyDbcAL-WW8',
    appId: '1:274514992002:ios:ae5baa9be24990da00cd9b',
    messagingSenderId: '274514992002',
    projectId: 'flutter-prime-df1c5',
    storageBucket: 'flutter-prime-df1c5.appspot.com',
    androidClientId: '274514992002-3bf319q74c3jhe9ib460dc0ovbnt4og5.apps.googleusercontent.com',
    iosClientId: '274514992002-sir5n1lsl1k41sehrqcd98ek6i7uf0ej.apps.googleusercontent.com',
    iosBundleId: 'dev.vlab.com.localCoin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn9i1S8g_2KAoMTrZ08PSkl-Xq1N4OW_Q',
    appId: '1:642335190187:web:42e9a0d573e85930929bee',
    messagingSenderId: '642335190187',
    projectId: 'localcoin-bae42',
    authDomain: 'localcoin-bae42.firebaseapp.com',
    storageBucket: 'localcoin-bae42.appspot.com',
    measurementId: 'G-DM1TSC7SS0',
  );

}